server:
  port: 8088
  servlet:
    context-path: /tijiancms
logging:
    level:
      org.springframework: debug
      com.neusoft.tijaincms: debug
      root: info


spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tijian?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.tijiancms.po,com.neusoft.tijiancms.dto